
import { MoodType, Intensity, MentalEffort, EnergyLevel, RecommendationMode, Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  fa: {
    title: 'Moodflix',
    subtitle: 'سینمای حالِ خوب شما',
    home: 'خانه سینما',
    profile: 'پروفایل من',
    saved: 'ذخیره شده‌ها',
    admin: 'پنل مدیریت',
    darkMode: 'حالت تاریک',
    lightMode: 'حالت روشن',
    step1Title: 'الان چه حسی داری؟',
    step1Subtitle: 'شدت و انرژی',
    step1More: 'کمی بیشتر بگو...',
    btnRecommend: 'دریافت پیشنهادات هوشمند',
    loading: 'در حال کشفِ دنیایِ شما...',
    loadingSub: 'هوش مصنوعی ما در حال بررسی هزاران فیلم برای پیدا کردن هماهنگ‌ترین گزینه‌ها با مودِ شماست.',
    tryAgain: 'تغییر مود و تلاش دوباره',
    noSaved: 'هنوز فیلمی ذخیره نکرده‌اید.',
    profileTitle: 'پروفایل احساسی',
    adminStats: 'آمار کل پلتفرم',
    adminUsers: 'مدیریت کاربران',
    adminSettings: 'تنظیمات API',
    adminMobile: 'توسعه موبایل (APK)',
    exportApk: 'استخراج نسخه اندروید (APK)',
    apkInstructions: 'آماده‌سازی پکیج نیتیو اندروید بر اساس PWA فعلی...',
    totalRequests: 'کل درخواست‌ها',
    aiSuccessRate: 'نرخ موفقیت AI',
    userName: 'نام کاربر',
    userStatus: 'وضعیت',
    userRole: 'نقش',
    loginTitle: 'ورود به مودفلیکس',
    registerTitle: 'عضویت در خانواده ما',
    email: 'ایمیل',
    password: 'رمز عبور',
    loginBtn: 'ورود',
    registerBtn: 'ثبت‌نام',
    noAccount: 'حساب کاربری ندارید؟ همین حالا عضو شوید',
    hasAccount: 'قبلاً عضو شده‌اید؟ وارد شوید',
    logout: 'خروج از حساب'
  },
  en: {
    title: 'Moodflix',
    subtitle: 'Your Cinema Therapy',
    home: 'Cinema Home',
    profile: 'My Profile',
    saved: 'Saved Movies',
    admin: 'Admin Panel',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    step1Title: 'How are you feeling?',
    step1Subtitle: 'Intensity & Energy',
    step1More: 'Tell us more...',
    btnRecommend: 'Get Smart Recommendations',
    loading: 'Discovering your world...',
    loadingSub: 'Scanning thousands of titles for you.',
    tryAgain: 'Change Mood & Retry',
    noSaved: 'No movies saved yet.',
    profileTitle: 'Emotional Profile',
    adminStats: 'Platform Analytics',
    adminUsers: 'User Management',
    adminSettings: 'API Settings',
    adminMobile: 'Mobile Deployment (APK)',
    exportApk: 'Export Android Package (APK)',
    apkInstructions: 'Generating Native Android package based on current PWA...',
    totalRequests: 'Total Requests',
    aiSuccessRate: 'AI Success Rate',
    userName: 'User Name',
    userStatus: 'Status',
    userRole: 'Role',
    loginTitle: 'Sign In to Moodflix',
    registerTitle: 'Join the Family',
    email: 'Email',
    password: 'Password',
    loginBtn: 'Sign In',
    registerBtn: 'Register',
    noAccount: 'New to Moodflix? Sign up now',
    hasAccount: 'Already a member? Sign In',
    logout: 'Logout'
  }
};

export const MOODS: any[] = [
  { type: 'happy', labels: { fa: 'خوشحال', en: 'Happy' }, icon: 'M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32l1.41 1.41M2 12h2m16 0h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41M12 7a5 5 0 100 10 5 5 0 000-10z', color: 'text-yellow-500' },
  { type: 'sad', labels: { fa: 'غمگین', en: 'Sad' }, icon: 'M20 17.58A5 5 0 0018 8h-1.26A8 8 0 104 16.25M8 16v.01M8 20v.01M12 18v.01M12 22v.01M16 16v.01M16 20v.01', color: 'text-blue-500' },
  { type: 'calm', labels: { fa: 'آرام', en: 'Calm' }, icon: 'M12 3a6 6 0 009 9 9 9 0 11-9-9z', color: 'text-teal-500' },
  { type: 'anxious', labels: { fa: 'مضطرب', en: 'Anxious' }, icon: 'M13 2L3 14h9l-1 8 10-12h-9l1-8z', color: 'text-purple-500' },
  { type: 'lonely', labels: { fa: 'تنها', en: 'Lonely' }, icon: 'M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z', color: 'text-indigo-500' },
  { type: 'angry', labels: { fa: 'عصبانی', en: 'Angry' }, icon: 'M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z', color: 'text-red-500' },
  { type: 'romantic', labels: { fa: 'عاشقانه', en: 'Romantic' }, icon: 'M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z', color: 'text-pink-500' },
];

export const INTENSITIES: any[] = [
  { value: 'low', labels: { fa: 'کم', en: 'Low' } },
  { value: 'medium', labels: { fa: 'متوسط', en: 'Medium' } },
  { value: 'high', labels: { fa: 'زیاد', en: 'High' } },
];

export const MODES: any[] = [
  { value: 'single', labels: { fa: 'تک پیشنهاد سریع', en: 'Quick Pick' } },
  { value: 'series', labels: { fa: 'سریال اپیزودیک', en: 'TV Series' } },
  { value: 'iranian', labels: { fa: 'سینمای ایران', en: 'Iranian Cinema' } },
  { value: 'mind-bending', labels: { fa: 'ذهن‌فریب', en: 'Mind-Bending' } },
];
